language: node_js
node_js:
  - "6.2.1"
os: osx
cache:
  directories:
  - node_modules
  - "$HOME/.nvm"
branches:
  only:
  - master
  - /^v?[0-9\\.]+/
install:
  - npm install
script:
  - npm run pack:mac
deploy:
  provider: releases
  api_key:
    secure: "sIwm52KcvtX447jiifHZLxGwxtcXBy2vBSQGxvQDtFDreQ3i2uu8Qp2E+3q6P6ijxqmt+wqEDbToIrFnD+G5Sc8BhhWW2w9phzTmPaOSnKgYekaojmwZudULlS/IbPjen7Be6vZOgZIL/gurMjKYVCmsAEcHqCkFJ9X/DmNrX+l6vkP3Mlk8ONIk+N4RwC9Iu0MgWYCwMJIP7Ys94ItFbreP4wdN8bln0Yn2ZMNr0X6OK8eYA4ProVmfJT39Ur/WmAWMfQMSsHwYiDbEhDzn6JkDaYuDnroIzCNS+aGgkMQxS1HUsNlH6YIlsLioPOMqdt4Hlaep/pHP7uAmZcjiKdPnIYK41GWclWX/6PJxUBtz7uNUNdhOxvyUqc2dSUc5ed7NlVIxVjrdaA8xmX4fnApyZ7kbtdn/BEJoyNtoy5iJJtCb6kWLdk+hnQI6XbgOHFChLdwjtC8MNtXyzEijBKmrxu/jj72U/G99guSsVpx5R661BnL6jtP9OgLfqU2LYZ0n3nH9kYP7Lca7Eklm/75vDu4eF5UopDqdGXbANC6twbI8b5KWSRv6/P3eHpb6qTRSdCnDM4jnktv5362SztLWIINbM8b3kapjVqBUlZ0nqUV+o39uZ6OP+3GGX5V10tFAGzL2ZqX8iBb5J38iOSCpOBrCcZgl15BHzGrfU0o="
  file:
    - dist/BlitzModder-$TRAVIS_TAG-mac.zip
    - dist/BlitzModder-$TRAVIS_TAG.dmg
  skip_cleanup: true
  on:
    repo: BlitzModder/BMPC
    tags: true
    branch: master
