language: node_js
node_js:
  - "6.2.1"
os: osx
cache:
  directories:
  - node_modules
  - "$HOME/.nvm"
branches:
  only:
  - master
  - /^v?[0-9\\.]+/
install:
  - npm install
script:
  - npm run pack:mac
deploy:
  provider: releases
  api_key:
    secure: "hclPX7AypbG20ux9nLvoSOnSJTqC3cDwZPt67h5M6oJyzV/00/RYbhGfJkJVrRcb/9IW/UZytYRMNNVVqmQdOyge+TynyGQSGDG1AMOtBTiUf4ZDdOPR0ehUJmAmPiQANkqjAVWYoEPjOon17uy/cpQ98U299nR2nj3A27G6ZAav8G0U/8GUAyDVOZ327c7ti5rb5Hw8SaIoQXlcDTxeAbI/pLMcMguJfbRGbpgIeIZPET7uNF81Zht0B7Jaeb1pGdBbYYlzWxulsdCsoRV9UyRKOV4K1WG6nFZTB5MsEA2OBF7DTe9Q0rNXgkChrCJt4WxoURRUbmMKdkcwuIXEqOQOMEf61DGQy5TzlClHTyoWWuxBQYhhXn7gUUWS1gQOp+OmBPLHY50LyBt8LuruJN8m6r3vCRBoHwdnl4YBPZ2/rqM/arQEAPvWIEg50JS8uHSHwiYii+k+LFS5KFvgRs+Xt5eSz1g9Y9JkDCnCMVIpWGtz5w0b13+ozcxI8SotWxdHDFHuVSbvHcItJyRu88dYYgVR7tAz0bCl4DB75gXVN3K8/dEDMyZAgvUkO7JRnrA0T+Ud0ag2YBRBeY0KFh8fojEewLYIeH1q091NFgdF4YmJaumOBJWKdx1T5tnMRzSjFY9PziSStu+3lFEoSviZHV9vavMgvIN/lCCf6Sk="
  file:
    - dist/mac/BlitzModder-$TRAVIS_TAG-mac.zip
    - dist/mac/BlitzModder-$TRAVIS_TAG-mac.dmg
  skip_cleanup: true
  on:
    repo: BlitzModder/BMPC
    tags: true
    branch: master
